//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMACadmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectRelease> ProjectReleases { get; set; }
        public virtual DbSet<ReqSet> ReqSets { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Env> Envs { get; set; }
        public virtual DbSet<MACRequest> MACRequests { get; set; }
        public virtual DbSet<Dept> Depts { get; set; }
    }
}
