//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMACadmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqSet
    {
        public ReqSet()
        {
            this.MACRequests = new HashSet<MACRequest>();
        }
    
        public int ReqSetID { get; set; }
        public Nullable<System.DateTime> ProjectID { get; set; }
        public Nullable<int> ReleaseID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string RoleID { get; set; }
        public string EnvID { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Env Env { get; set; }
        public virtual ProjectRelease ProjectRelease { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<MACRequest> MACRequests { get; set; }
    }
}
